---
- name: Setup networking
  hosts: internal_networked
  become: true
  roles:
    - role: persist_route
      vars:
        persist_route_routes:
          - interface: eth1
            to: 10.0.0.0/8
            via: 10.80.0.1

  tasks:
    - name: Check if /etc/netplan/50-cloud-init.yaml exists
      ansible.builtin.stat:
        path: /etc/netplan/50-cloud-init.yaml
      register: ansible_builtin_stat_result

    - name: Set permissions on /etc/netplan/50-cloud-init.yaml if it exists
      ansible.builtin.file:
        path: /etc/netplan/50-cloud-init.yaml
        mode: "0600"
      when: ansible_builtin_stat_result.stat.exists
      register: set_perm_result
