---
- name: Update apt packages and ensure qemu-guest-agent is installed
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade all apt packages
      ansible.builtin.apt:
        upgrade: full

    - name: Ensure qemu-guest-agent is installed
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present

    - name: Include create_user role
      ansible.builtin.import_role:
        name: create_user
      vars:
        create_user_name: admin
        create_user_password: ""
